import intf_libs = spirv-cross-glsl%lib{spirv-cross-glsl}
impl_libs = # Implementation dependencies.

lib{spirv-cross-hlsl}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base/"

{hbmia obja}{*}: cxx.poptions += -DSPIRV_CROSS_HLSL_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DSPIRV_CROSS_HLSL_SHARED_BUILD

# Export options.
#
lib{spirv-cross-hlsl}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base/"
  cxx.export.libs = $intf_libs
}

liba{spirv-cross-hlsl}: cxx.export.poptions += -DSPIRV_CROSS_HLSL_STATIC
libs{spirv-cross-hlsl}: cxx.export.poptions += -DSPIRV_CROSS_HLSL_SHARED

# Install into the spirv-cross-hlsl/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
}
