intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{spirv-cross-core}: {hxx ixx txx cxx}{**} hxx{GLSL.std.450.h} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base/"

{hbmia obja}{*}: cxx.poptions += -DSPIRV_CROSS_CORE_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DSPIRV_CROSS_CORE_SHARED_BUILD

# Export options.
#
lib{spirv-cross-core}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base/"
  cxx.export.libs = $intf_libs
}

liba{spirv-cross-core}: cxx.export.poptions += -DSPIRV_CROSS_CORE_STATIC
libs{spirv-cross-core}: cxx.export.poptions += -DSPIRV_CROSS_CORE_SHARED

# Install into the spirv-cross-core/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
}
