import intf_libs = spirv-cross-glsl%lib{spirv-cross-glsl}
impl_libs = # Implementation dependencies.

lib{spirv-cross-reflect}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base/"

{hbmia obja}{*}: cxx.poptions += -DSPIRV_CROSS_REFLECT_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DSPIRV_CROSS_REFLECT_SHARED_BUILD

# Export options.
#
lib{spirv-cross-reflect}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base/"
  cxx.export.libs = $intf_libs
}

liba{spirv-cross-reflect}: cxx.export.poptions += -DSPIRV_CROSS_REFLECT_STATIC
libs{spirv-cross-reflect}: cxx.export.poptions += -DSPIRV_CROSS_REFLECT_SHARED

# Install into the spirv-cross-reflect/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
}
